services:
  jupyter:
    build: 
      context: ./.docker
      dockerfile: Dockerfile
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/workspace
      - ./jupyter-config:/root/.jupyter
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        limits:
            memory: 4g
        reservations:
          devices:
            - capabilities:
              - gpu